version: '3.4'

services:
  app:
    image: codespacesprojecttemplatepy
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
      - ./DataRequestor:/app/DataRequestor
    ports:
      - "9000:9000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=0
    command: ["flask", "run", "--host=0.0.0.0", "--port=9000"]
